---

- name: NGINX Ingress Controller | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/ingress_nginx"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: NGINX Ingress Controller | Create manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/ingress_nginx/{{ item.file }}"
  with_items:
    - { name: ingress-nginx-ns, file: ingress-nginx-ns.yml, type: ns }
    - { name: ingress-nginx-sa, file: ingress-nginx-sa.yml, type: sa }
    - { name: ingress-nginx-role, file: ingress-nginx-role.yml, type: role }
    - { name: ingress-nginx-rolebinding, file: ingress-nginx-rolebinding.yml, type: rolebinding }
    - { name: ingress-nginx-clusterrole, file: ingress-nginx-clusterrole.yml, type: clusterrole }
    - { name: ingress-nginx-clusterrolebinding, file: ingress-nginx-clusterrolebinding.yml, type: clusterrolebinding }
    - { name: ingress-nginx-cm, file: ingress-nginx-cm.yml, type: cm }
    - { name: ingress-nginx-default-backend-svc, file: ingress-nginx-default-backend-svc.yml, type: svc }
    - { name: ingress-nginx-default-backend, file: ingress-nginx-default-backend.yml, type: deployment }
    - { name: ingress-nginx-controller, file: ingress-nginx-controller.yml, type: deployment }
    - { name: ingress-nginx-rule, file: ingress-nginx-rule.yml, type: ingress }
    - { name: ingress-nginx-controller-svc, file: ingress-nginx-controller-svc.yml, type: svc }
  register: ingress_nginx_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: NGINX Ingress Controller | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ ingress_nginx_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ kube_config_dir }}/addons/ingress_nginx/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ ingress_nginx_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
